  name: Build Docker
  on: push
  jobs:
    Docker-build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout
        - run: docker build -t nginx_server_test . --file Dockerfile
